<?php
/**
 * Implements hook_menu().
 */
function edgemakers_user_menu() {
  $items['edgemakers/user/profile/ajax/%user'] = array(
    'page callback' => 'edgemakers_user_view', // Render HTML
    'page arguments' => array(4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'edgemakers_user.pages.inc',
  );
  return $items;
}
/**
 * Implements hook_form_alter().
 */
function edgemakers_user_form_alter(&$form, &$form_state, $form_id) {
  if(arg(0) == 'modal_forms' 
    && ($form_id == 'user_register_form' || $form_id == 'user_login' || $form_id == 'user_pass')
    && variable_get('modal_forms_login_links', 0) == 3) {
    $items = array();
    if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)) {
      $items[] = array('data'=>ctools_modal_text_button(t('Create new account'), 'modal_forms/nojs/register', t('Create a new user account'), 'ctools-modal-modal-popup-medium'.($form_id == 'user_register_form' ? ' active':'')), 'class'=>array('user_register_form'));
    }
    $items[] = array('data'=>ctools_modal_text_button(t('Log in'), 'modal_forms/nojs/login', t('Log in.'), 'ctools-modal-modal-popup-small'.($form_id == 'user_login' ? ' active':'')), 'class'=>array('user_login'));
    $items[] = array('data'=>ctools_modal_text_button(t('Request new password'), 'modal_forms/nojs/password', t('Request new password via e-mail.'), 'ctools-modal-modal-popup-small'.($form_id == 'user_pass' ? ' active':'')), 'class'=>array('user_pass'));
    $form['tabs'] = array('#markup' => theme('item_list', array('items' => $items)), '#weight' => -100);
  }
  switch ($form_id) {
    case 'modal_forms_admin_settings':
      $form['modal_forms_login_settings']['modal_forms_login_links']['#options'][3] = t('Show links above and open them in a modal');
      break;
    case 'user_register_form':
      //if (arg(0) == 'modal_forms') {
        //print_r($form);
        unset($form['account']['name']['#title'], $form['account']['name']['#description'], $form['account']['mail']['#title'], $form['account']['mail']['#description'], $form['account']['pass']['#description'], $form['picture']['#title'], $form['picture']['picture_upload']['#description'], $form['field_firstname'][LANGUAGE_NONE][0]['value']['#title'], $form['field_firstname'][LANGUAGE_NONE][0]['value']['#description'], $form['field_lastname'][LANGUAGE_NONE][0]['value']['#title'], $form['field_lastname'][LANGUAGE_NONE][0]['value']['#description']);
        $form['account']['name']['#attributes']['placeholder'] = t('USER NAME');
        $form['account']['mail']['#attributes']['placeholder'] = t('EMAIL');
        $form['account']['mail']['#weight'] = -11;
        $form['field_firstname'][LANGUAGE_NONE][0]['value']['#attributes']['placeholder'] = t('FIRST NAME');
        $form['field_lastname'][LANGUAGE_NONE][0]['value']['#attributes']['placeholder'] = t('LAST NAME');
        $form['actions']['submit']['#value'] = t('Continue ->');
        $element_info = element_info('password_confirm');
        $process = $element_info['#process'];
        // Add our process function to the array:
        $process[] = 'edgemakers_user_process_password_confirm';
        $form['account']['pass']['#process'] = $process;
      //}
      break;
    case 'user_login':
      if (arg(0) == 'modal_forms') {
        unset($form['name']['#title'], $form['name']['#description'], $form['pass']['#title'], $form['pass']['#description']);
        $form['name']['#attributes']['placeholder'] = t('USER NAME');
        $form['pass']['#attributes']['placeholder'] = t('PASSWORD');
        $form['actions']['submit']['#value'] = t('Log in ->');
      }
      break;
    case 'user_pass':
      if (arg(0) == 'modal_forms') {
        unset($form['name']['#title'], $form['name']['#description']);
        $form['name']['#attributes']['placeholder'] = t('USER NAME OR EMAIL');
        $form['actions']['submit']['#value'] = t('Email New Password ->');
      }
      break;
  }
}
function edgemakers_user_process_password_confirm($element) {
  unset($element['pass1']['#title'], $element['pass2']['#title']);
  $element['pass1']['#attributes']['placeholder'] = t('PASSWORD');
  $element['pass2']['#attributes']['placeholder'] = t('CONFIRM PASSWORD');
  return $element;
}
/*function edgemakers_user_module_implements_alter(&$implementations, $hook) {
  print_r($hook);
  if ($hook == 'form_user_register_form_alter') {
  print_r($implementations);
    $implementation = $implementations['avatar_selection'];
    unset($implementations['avatar_selection']);
    array_unshift($implementations['avatar_selection'], $implementation);
  }
}*/