<?php

/**
 * Implements hook_menu().
 */
function fte_curriculum_menu() {
  $items['learn'] = array(
      'page callback' => 'learnnavpage',
      'access callback' => TRUE,
      'file' => 'fte_learn.inc',
  );

  $items['learn/%/stage/%'] = array(
      'page callback' => 'fte_modulestage_view',
      'page arguments' => array(1, 3),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'fte_learn.inc',
  );


  return $items;
}
function fte_curriculum_page_alter(&$page) {
  global $is_showstage_page;
  if (isset($is_showstage_page) && $is_showstage_page == 1) {
    //unset($page['page_top']);
    //unset($page['page_bottom']);
    //unset($page['sidebar_first']);
     //unset($page['sidebar_second']);
    
  }
  
}
function fte_curriculum_theme($existing, $type) {
  if ($type == 'module') {
    return array(
        'fte_learn_nav' => array(
            'variables' => array('data' => NULL),
            'template' => 'templates/fte-learn-nav',
        ),
        'fte_learn_module_stage_show' => array(
            'variables' => array('data' => NULL),
            'template' => 'templates/fte-learn-module-stages-show',
        ),
        'fte_learn_module_stage_bottom_style_1' => array(
            'variables' => array('data' => NULL),
            'template' => 'templates/fte-stages-style-1',
        ),
        'fte_learn_module_stage_bottom_style_2' => array(
            'variables' => array('data' => NULL),
            'template' => 'templates/fte-stages-style-2',
        ),
        'fte_learn_module_stage_bottom_style_3' => array(
            'variables' => array('data' => NULL),
            'template' => 'templates/fte-stages-style-3',
        ),
        'fte_learn_module_stage_bottom_style_4' => array(
            'variables' => array('data' => NULL),
            'template' => 'templates/fte-stages-style-4',
        ),
        'fte_learn_module_stage_right' => array(
            'variables' => array('data' => NULL),
            'template' => 'templates/fte-stages-right',
        ),
    );
  }
  return array();
}

function fte_curriculum_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {

    case 'stage_assignment_template_node_form':
    case 'stages_template2_node_form':  //video stage
    case 'stage_mural_template_node_form':
    case 'stages_template1_node_form':  //text stage
      $lan = isset($form['field_introduction_video']['#language']) ? $form['field_introduction_video']['#language'] : 'und';
      $form['field_introduction_video'][$lan]['#element_validate'][] = '_fte_youtube_url_check';
      $form['field_tour_guide'][$lan]['#element_validate'][] = '_fte_youtube_url_check';
      if ($form_id == 'stages_template2_node_form') {
        $form['field_video_key'][$lan]['#element_validate'][] = '_fte_youtube_url_check';
      }
      break;
  }
}

function _fte_youtube_url_check($element, &$form_state) {
  $themax = (int) $element['#max_delta'];

  for ($i = 0; $i <= $themax; $i++) {
    if (empty($element[$i]['value']['#value']) || !valid_url($element[$i]['value']['#value'])) {
      form_error($element[$i], t('The "!name"  must contain a valid url. You may either leave the text field empty or enter a string like "http://www.youtube.com/watch?v=DzgK96E3i60"', array('!name' => t($element['#title']))));
    }
  }
}

