<?php

/**
 * Implements hook_menu().
 */
function fte_curriculum_menu() {
  $items['learn'] = array(
    'page callback' => 'learnnavpage',
    'access callback'=> TRUE,
    'file' => 'fte_learn.inc',      
  );
  
  $items['learn/%/stage/%'] = array(
    'page callback' => 'fte_modulestage_view',
    'page arguments' => array(1,3),  
    'access callback'=> TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'fte_learn.inc',      
  );
  
  
  return $items;
}

function fte_curriculum_theme($existing, $type) {
  if ($type == 'module') {
    return array(
      'fte_learn_nav' => array(
        'variables' => array('data' => NULL),
        'template' => 'templates/fte-learn-nav',
      ),
      'fte_learn_module_stage_show' => array(
        'variables' => array('data' => NULL),
        'template' => 'templates/fte-learn-module-stages-show',
      ),
      
    );
  }
  return array();
}


