<?php

/**
 * Implements hook_menu().
 */
function ftestaticpage_menu() {

  $items['pageview/%node'] = array(
      'page callback' => 'page_view',
      'page arguments' => array(1),
      'access callback' => 'user_is_logged_in',
      'type' => MENU_CALLBACK,
  );


  return $items;
}

function page_view($node) {
  
}

function ftestaticpage_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'static_page_node_form') {
    $langcode = isset($form['#language']) ? $form['#language'] : 'und';
    $r_list = user_roles(TRUE);
    $roles_array = array();
    $del_roles = array('authenticated user', 'site administrator', 'site admin');
    foreach ($r_list as $k => $v) {
      if (!in_array($v, $del_roles)) {
        $roles_array[$k] = $v;
      }
    }
    unset($r_list);
    if (!empty($roles_array)) {
      $form['field_user_role'][$langcode]['#options'] = $roles_array;
    }
  }
}