<?php
/**
 * @file
 * This module creates a Views Slideshow Xtra content type and
 * example slide nodes.
 */

/**
 * Implements hook_init().
 */
function edgemakers_stage_init () {
  //drupal_add_css(drupal_get_path("module", "tt")."/tt.css");
}

/**
 * Implements hook_menu().
 */
function edgemakers_stage_menu() {

  $items = array();

  // Module settings.
  $items['admin/config/system/ftesettings/edgemakers'] = array(
    'title' => 'Edgemakers Stage',
    'description' => 'settings for Stage',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('edgemakers_stage_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'edgemakers_stage') . '/inc',
  );

  $items['admin/edgemakers/stage/setindex/ajaxdelete/%'] = array(
    'title' => 'Delete Set',
    'page callback' => 'edgemakers_set_index_delete_action',
    'page arguments' => array(5, 6),
    'access arguments' => array('access content'),
    'file path' => drupal_get_path('module', 'node'),
    'file' => 'node.pages.inc',
  );

  // Page tab menu
  $items['admin/edgemakers/stage'] = array(
    'title' => 'Manage Stage',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'edgemakers_stage_page',
    'access arguments' => array('access content'),
  );

  $items['admin/edgemakers/stage/list'] = array(
    'title' => 'Manage stage',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'page callback' => 'edgemakers_stage_page',
    'access arguments' => array('access content'),
  );

  $items['admin/edgemakers/stage/create'] = array(
    'title' => 'Create Stage',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'edgemakers_stage_create',
    'access arguments' => array('access content'),
  );

  $items['admin/edgemakers/stage/managebox'] = array(
    'title' => 'Manage Box',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'edgemakers_stage_page_managebox',
    'page arguments' => array(4),
    'access arguments' => array('access content'),
  );

  /*$items['admin/edgemakers/stage/%/edit'] = array(
    'title' => 'Edit Layout',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'edgemakers_stage_edit',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
  );*/

  return $items;

}

function edgemakers_stage_theme() {
  return array(
    'edgemakers_stage_set_list_form' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_foo().
 *
 * Displays help and module information.
 */
function edgemakers_stage_help($path, $arg) {
  switch ($path) {
    case "admin/help#stage":
      $help_test = '<p>' . t("Admin stage of set.") . '</p>';

      return $help_test;

      break;
  }
}

/**
 * edgemakers_stage_page()
 *   - Layout admin page.
 */
function edgemakers_stage_page() {

  ctools_include('modal');
  ctools_modal_add_js();
  $type = variable_get('edgemakers_stage_content_type', 'stage');
  $nodes = node_load_multiple(array(), array('type' => $type));
  $header = array(
    'title' => array('data' => t('Set Title')),
    'dimension' => array('data' => t('Dimension')),
    'operations' => t('Operations'),
  );

  $options = array();
  foreach ($nodes as $node) {

    $langcode = entity_language('node', $node);
    $l_options = $langcode != LANGUAGE_NONE && isset($languages[$langcode]) ? array('language' => $languages[$langcode]) : array();
    $destination = drupal_get_destination();

    // Dimension.
    if (isset($node->dimension_x[LANGUAGE_NONE])) {
      $dimension_x = $node->dimension_x[LANGUAGE_NONE][0]['value'];
    }
    if (isset($node->dimension_y[LANGUAGE_NONE])) {
      $dimension_y = $node->dimension_y[LANGUAGE_NONE][0]['value'];
    }

    $dimension = $dimension_x . " X " . $dimension_y;

    // Operations.
    $edit_url = l('Edit',
      'modal/node/' . $node->nid . '/edit/nojs/1',
      array(
        'query' => array(
          'destination' => drupal_get_destination(),
        ),
        'attributes' => array(
          'class' => array('ctools-use-modal'),
        ),
      )
    );
    $managebox_url = l('Manage Box', 'admin/edgemakers/stage/managebox/' . $node->nid);
    $delete_url = l('Delete', 'node/' . $node->nid . '/delete',
      array(
        'query' => array(
          'destination' => drupal_get_destination(),
        )
      )
    );

    $options[$node->nid] = array(
      'title' => check_plain($node->title),
      'dimension' => $dimension,
      'operations' => $delete_url . ' | ' . $edit_url . ' | ' . $managebox_url
    );
  }
  $form['nodes'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $options,
    '#empty' => t('No content available.'),
  );
  $form['pager'] = array('#markup' => theme('pager'));
  $form['#prefix'] = '<div id="setesListDiv">';
  $form['#suffix'] = '</div>';
  return $form;
}

/**
 * edgemakers_stage_create()
 *   - Create new layout page.
 * @return string
 */
function edgemakers_stage_create() {
  module_load_include('inc', 'node', 'node.pages');
  $form = node_add('stage');
  unset($form['box_index_data']);
  $output = drupal_render($form);
  return $output;
}

/**
 * edgemakers_stage_edit()
 *   - Edit layout page.
 * @return string
 */
function edgemakers_stage_edit($nid = '') {
  if ($nid) {
    module_load_include('inc', 'node', 'node.pages');
    $node = node_load($nid);
    $form = drupal_get_form('node_form', $node);
    $output = drupal_render($form);
    return $output;
  }
  else {
    drupal_goto('admin/edgemakers/stage/create');
  }

}

/**
 * Mangement box index.
 * @return string
 */
function edgemakers_stage_page_managebox($sid = '') {

  //$output = 'edgemakers_stage_page_managebox';
  drupal_add_library('system', 'drupal.ajax');
  ctools_include('modal');
  ctools_modal_add_js();

  $output = '';

  if ($sid) {
    $form = drupal_get_form('edgemakers_stage_managebox_form');
    /*$form['stage_id'] = array(
      '#name' => 'stage_id',
      '#type' => 'textfield',
      '#value' => $sid,
    );*/
    $output .= drupal_render($form);

    $list_form = drupal_get_form('edgemakers_stage_set_list_form', $sid);

    $output .= '<div id="stage_manage_box_index_list">';
    $output .= drupal_render($list_form);
    $output .= '</div>';

  }
  else {
    drupal_goto('admin/edgemakers/stage');
  }

  return $output;
}

/**
 * Implements hook_form();
 */
function edgemakers_stage_managebox_form($form, &$form_state) {

  $form = array();

  $sid = arg(4);

  $form['stage_id'] = array(
    '#type' => 'hidden',
    '#default_value' => $sid,
  );

  $vid = variable_get('edgemakers_set_type_term', 1);

  $terms_tree = taxonomy_get_tree($vid);
  foreach ($terms_tree as $ter) {
    $perfix = '';
    for ($i = 0; $i < $ter->depth; $i++) {
      $perfix .= '-';
    }
    $terms_optins[$ter->tid] = $perfix . $ter->name;
  }

  // Get the list of options to populate the first dropdown.
  $options_first = $terms_optins;
  // If we have a value for the first dropdown from $form_state['values'] we use
  // this both as the default value for the first dropdown and also as a
  // parameter to pass to the function that retrieves the options for the
  // second dropdown.
  $selected = isset($form_state['values']['set_types']) ? $form_state['values']['set_types'] : key($options_first);

  $form['Set_Fields'] = array(
    '#type' => 'fieldset',
  );

  $form['Set_Fields']['set_types'] = array(
    '#type' => 'select',
    '#title' => 'Set Type',
    '#options' => $options_first,
    '#default_value' => $selected,

    // Bind an ajax callback to the change event (which is the default for the
    // select form type) of the first dropdown. It will replace the second
    // dropdown when rebuilt
    '#ajax' => array(
      // When 'event' occurs, Drupal will perform an ajax request in the
      // background. Usually the default value is sufficient (eg. change for
      // select elements), but valid values include any jQuery event,
          // most notably 'mousedown', 'blur', and 'submit'.
          // 'event' => 'change',
          'callback' => '_ajax_set_types_dropdown_callback',
          'wrapper' => 'dropdown-title-replace',
      ),
  );

  $form['Set_Fields']['set_title'] = array(
    '#type' => 'select',
    '#title' => t('Set Title'),

    // The entire enclosing div created here gets replaced when dropdown_first
    // is changed.
    '#prefix' => '<div id="dropdown-title-replace">',
    '#suffix' => '</div>',

    // when the form is rebuilt during ajax processing, the $selected variable
    // will now have the new value and so the options will change
    '#options' => _ajax_get_set_title_dropdown_options($selected),
    '#default_value' => isset($form_state['values']['set_title']) ? $form_state['values']['set_title'] : '',
  );

  $form['Set_Fields']['set_location_index'] = array(
    '#type' => 'textfield',
    '#title' => 'Set Location Index',
    '#required' => false,
  );

  $form['add_set_to_stage'] = array(
    '#type' => 'submit',
    '#value' => t('Add set to stage'),
  );


  return $form;

}

/**
 *
 * @param unknown_type $sid
 */
function edgemakers_stage_default_set_list_table($sid) {
  $output = '';
  $sets = node_load($sid);
  $output = stage_list_table($sid);
  return $output;
}

/**
 * Get dropdown callback;
 * @param unknown_type $form
 * @param unknown_type $form_state
 */
function _ajax_set_types_dropdown_callback($form, $form_state) {
  return $form['Set_Fields']['set_title'];
}

/**
 * Get title options list by AJAX.
 * @param int $tid
 * @return Ambigous <An, multitype:>|multitype:
 */
function _ajax_get_set_title_dropdown_options($tid = '') {

  if ($tid) {
    if ($nids = taxonomy_select_nodes($tid)) {
      $set_options = array();
      $nodes = node_load_multiple($nids);
      foreach ($nodes AS $n) {
        $set_options[$n->nid . ':' . $n->title ] = $n->title;
      }
      return $set_options;
    }
  }

  return array();

}

/**
 * Implements hook_form_validate();
 */
function edgemakers_stage_managebox_form_validate($form, &$form_state) {

  $values = $form_state['values'];
  $set_info = explode(':', $values['set_title']);

  $set_nid = isset($set_info[0])?$set_info[0]:0;
  $set_title = isset($set_info[1])?$set_info[1]:' ';

  if (_has_set_in_stage($values['stage_id'], $set_nid)) {
    form_set_error('set_title', t('Set "@set" has in Stage now.', array('@set' => $set_title)));
  }
}

/**
 *
 * @param int $stage_id
 * @param int $set_id
 */
function _has_set_in_stage($stage_id = '', $set_id = '') {

  if ($stage_id && $set_id) {
    $stage = node_load($stage_id);

    if (isset($stage->box_index_data[LANGUAGE_NONE])) {
      $node_box_index_data = unserialize($stage->box_index_data[LANGUAGE_NONE][0]['value']);
      foreach ($node_box_index_data AS $index) {
        if ($index['set_id'] == $set_id) {
          return true;
        }
      }
      return false;
    }
    else {
      return false;
    }

  }
}


/**
 * Implements hook_form_submit();
 */
function edgemakers_stage_managebox_form_submit($form, &$form_state) {

  global $user;

  // Form data.

  if (empty($form_state['values']['set_location_index'])) {
    $form_state['values']['set_location_index'] = 0;
  }

  $values = $form_state['values'];

  $set_info = explode(':', $values['set_title']);

  $set_nid = isset($set_info[0])?$set_info[0]:0;

  $ignore = array('form_build_id','form_token','form_id','op','submit', 'set_types', 'set_title');

  // Stage node data.
  $node = node_load($form_state['values']['stage_id']);

  if (isset($node->box_index_data[LANGUAGE_NONE])) {
    $node_box_index_data = unserialize($node->box_index_data[LANGUAGE_NONE][0]['value']);
  }
  else {
    $node_box_index_data = array();
  }

  $node_box_index_data[] = array(
    'stage_id' => $form_state['values']['stage_id'],
    'set_id' => $set_nid,
    'location_index' => $form_state['values']['set_location_index'],
  );

  $values['box_index_data'] = serialize($node_box_index_data);

  //Loop through the values
  foreach ($values as $key => $value)
  {
    if (in_array($key, $ignore)) continue;
    $node->{$key}[$node->language][0]['value'] = $value;
  }


  $submit_status = node_submit($node);
  $save_status = node_save($node);

  //drupal_set_message('<pre>' . print_r($save_status, TRUE) . '</pre>');

}

/**
 *
 */
function _add_set_to_stage_ajax($form, &$form_state) {

  $tableitem = $form_state['values']['set_title'];
  $datas = $form_state['values'];

  if (!in_array($tableitem, $_SESSION['lists'][$datas->stage_id])) {
    $_SESSION['lists'][$datas->stage_id][] = array(
      'nid' => $form_state['values']['set_title'],
      'title' => $form_state['values']['set_title'],
      'type' => $form_state['values']['set_types'],
      'location' => $form_state['values']['set_location_index'],
    );
  }

  //for ($i = 1; $i < $form_state['num_names']; $i++) {

  $header = array(
    'title' => array('data' => t('Set Title')),
    'type' => array('data' => t('Set Type')),
    'location' => array('data' => t('Set Location')),
    'operations' => t('DELETE'),
  );
  foreach ($_SESSION['lists'][$datas->stage_id] AS $set) {

    if ($set['nid']) {
  //drupal_set_message('<pre>' . print_r($set, TRUE) . '</pre>');
      $form['set_list']['set_list_table']['set_nid_' . $set['nid']] = array(
        '#type' => 'textfield',
        '#title' => t('SEt ' . $key),
        '#value' => $set['nid'],
        //'#prefix' => '<div style="float: left;">',
        //'#suffix' => '</div>',
      );
      $form['set_list']['set_list_table']['set_type_' . $set['nid']] = array(
        '#type' => 'textfield',
        '#title' => t('Type ' . $key),
        '#value' => $set['type'],
        //'#prefix' => '<div style="float: left;">',
        //'#suffix' => '</div>',
      );
      $form['set_list']['set_list_table']['set_location_' . $set['nid']] = array(
        '#type' => 'textfield',
        '#title' => t('Box location index ' . $key),
        '#value' => $set['location'],
        //'#prefix' => '<div style="float: left;">',
        //'#suffix' => '</div>',
      );
    }

  }
  //unset($_SESSION['lists']);
  //unset($_SESSION['lists'][$datas->stage_id][]);
  return $form['set_list']['set_list_table'];
}

/**
 * Implements hook_form_alter().
 */
function edgemakers_stage_form_alter(&$form, $form_state, $form_id) {
  $type = str_replace("-", "_" ,variable_get('edgemakers_stage_content_type', 'stage'));
  $stage_form_id = $type . '_node_form';

  //drupal_set_message($stage_form_id);
  //$stage_delete_form_id = $type . 'node_delete_confirm';

  if ($form_id == $stage_form_id) {

    if ((arg(1) == 'edgemakers' && arg(2) == 'stage')
      || (arg(0) == 'modal')
    ) {

      $form['actions']['submit']['#submit'][] = '_edgemakers_stage_node_submit_redirect_handler';
      $form['#redirect'] = 'admin/edgemakers/set';

      unset($form['actions']['preview']);
      unset($form['actions']['delete']);
      unset($form['box_index_data']);

    }
  }
}

/**
 * handler form submit.
 */
function _edgemakers_stage_node_submit_redirect_handler($form, &$form_state) {
  unset($_REQUEST['destination']);
  unset($form['#redirect']);
  //$node = $form_state['node'];
  //if (!isset($node->nid)) {
  $form_state['redirect'] = 'admin/edgemakers/stage';
  //}
}

/**
 *
 */
function edgemakers_stage_set_list_form($form, &$form_state, $stage_id = '') {

  $stage = node_load($stage_id);

  //if (empty($stage_id)) {
  //  $stage_id = $_SESSION['stage_id_in_set_list_form'];
  //}

  if (isset($stage->box_index_data[LANGUAGE_NONE])) {
    $nodes = array();
    $stage_index = unserialize($stage->box_index_data[LANGUAGE_NONE][0]['value']);

    //drupal_set_message('Stage Index before sort: <pre>' . print_r($stage_index, TRUE) . '</pre>');

    //uasort($stage_index, 'location_index');

    $stage_index_sort = array();
    foreach ($stage_index as $key => $row)
    {
      $stage_index_sort[$key] = $row['location_index'];
    }
    array_multisort($stage_index_sort, SORT_ASC, $stage_index);

    //drupal_set_message('Stage Index after sort: <pre>' . print_r($stage_index, TRUE) . '</pre>');

    foreach ($stage_index AS $index) {
      $nid = !empty($index['set_id'])?$index['set_id']:0;
      if ($nid) {
        $node = node_load($nid);
        $node->weight = $index['location_index'];

        // Get box type by tid.
        if (isset($node->field_set_type[LANGUAGE_NONE])) {
          $node->tname = taxonomy_term_load($node->field_set_type[LANGUAGE_NONE][0]['tid']);
          //drupal_set_message('Term name (location_index): <pre>' . print_r($node->tname, TRUE) . '</pre>');
        }

        //drupal_set_message('weight (location_index): ' . $index['location_index']);
        $nodes[] = $node;
      }
    }

    $results = $tree = $nodes;

  }

  $header = array(
    'title' => array('data' => t('Set Title')),
    'type' => array('data' => t('Set Type')),
    'weight' => t('Weight'),
  );

  $options = array();

  $operations = array('delete' => t('Delete'));

  $form['#tree'] = TRUE;
  $form['stage_id'] = array(
    '#type' => 'hidden',
    '#value' => $stage_id,
  );

  // Fetch the example data from the database, ordered by weight ascending.
  //
  // This query excludes the last two tabledrag_example database rows, as
  // they are intended only for the 'parent/child' tabledrag examples.
  // $result = db_query('SELECT id, name, description, weight FROM {tabledrag_example} WHERE id < 8 ORDER BY weight ASC');

  // Iterate through each database result.
  if (isset($results)) {
    foreach ($results as $item) {

    // Create a form entry for this item.
      //
      // Each entry will be an array using the the unique id for that item as
      // the array key, and an array of table row data as the value.
      $form['set_' . $item->nid] = array(

        // We'll use a form element of type '#markup' to display the item name.
        'name' => array(
          '#markup' => check_plain($item->title),
        ),

        // We'll use a form element of type '#textfield' to display the item
        // description, which will allow the value to be changed via the form.
        // We limit the input to 255 characters, which is the limit we set on
        // the database field.
        'type' => array(
          '#markup' => check_plain($item->tname->name),
        ),

        'operations' => array(
          '#type' => 'link',
          '#title' => t('delete'),
          '#href' => 'admin/edgemakers/stage/setindex/ajaxdelete/' . $stage_id . '/' . $item->nid . '/nojs/1',
          '#attributes' => array('class' => array('use-ajax')),
        ),

        // The 'weight' field will be manipulated as we move the items around in
        // the table using the tabledrag activity.  We use the 'weight' element
        // defined in Drupal's Form API.
        'weight' => array(
          '#type' => 'weight',
          '#title' => t('Weight'),
          '#default_value' => $item->weight,
          '#delta' => 10,
          '#title-display' => 'invisible',
        ),
      );

    }
  }

  // Now we add our submit button, for submitting the form results.
  //
  // The 'actions' wrapper used here isn't strictly necessary for tabledrag,
  // but is included as a Form API recommended practice.
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Changes'),
  );

  return $form;


  /*$form['options']['operation'] = array(
    '#type' => 'select',
    '#title' => t('Operation'),
    '#title_display' => 'invisible',
    '#options' => $operations,
    '#default_value' => 'approve',
  );

  foreach ($nodes as $node) {
    $edit_weight_url = l('edit', '#', array('attributes' => array('id' => 'weight_edit_'.$node->nid)));
    $options[$node->nid] =array(
      'title' => $node->title,
      'type' => $node->tname->name,
      'weight' => $node->weight . '(' . $edit_weight_url . ')',
    );
  }

  $form['table'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $options,
    '#empty' => t('No users found'),
  );
  */

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update Stage'),
    '#validate' => array('edgemakers_stage_set_list_form_validate'),
    '#submit' => array('edgemakers_stage_set_list_form_submit'),
  );

  return $form;

}

function edgemakers_stage_set_list_form_validate($form, &$form_state) {

}


function edgemakers_stage_set_list_form_submit($form, &$form_state) {

  $values = $form_state['values'];

  //$_SESSION['stage_id_in_set_list_form'] = $values['stage_id'];

  //drupal_set_message('<pre>' . print_r($values, TRUE) . '</pre>');

  $stage = node_load($values['stage_id']);

  if (isset($stage->box_index_data[LANGUAGE_NONE])) {

    $stage_index = unserialize($stage->box_index_data[LANGUAGE_NONE][0]['value']);

    foreach ($stage_index AS $key=>$index) {
      $location_index = $values['set_' . $index['set_id']];
      $stage_index[$key]['location_index'] = $values['set_' . $index['set_id']]['weight'];
      //drupal_set_message('<pre>' . print_r($location_index, TRUE) . '</pre>');
      //$stage_index[$key]
    }

    //unset($stage_index[$set_id]);

    //$stage['box_index_data'] = serialize($stage_index);
    // Update index data in stage.
    $stage->box_index_data[$stage->language][0]['value'] = serialize($stage_index);

    node_submit($stage);
    $save_status = node_save($stage);

    //_edgemakers_stage_box_index_list_update($stage_id);

  }

}


function theme_edgemakers_stage_set_list_form($variables) {

  $form = $variables['form'];

  // Initialize the variable which will store our table rows.
  $rows = array();

  //drupal_set_message('Form: <pre>' . print_r($form, TRUE) . '</pre>');

  // Iterate over each element in our $form['example_items'] array.
  foreach (element_children($form) as $id) {

    // Before we add our 'weight' column to the row, we need to give the
    // element a custom class so that it can be identified in the
    // drupal_add_tabledrag call.
    //
    // This could also have been done during the form declaration by adding
    // '#attributes' => array('class' => 'example-item-weight'),
    // directy to the 'weight' element in tabledrag_example_simple_form().
    $form[$id]['weight']['#attributes']['class'] = array('example-item-weight');

    // We are now ready to add each element of our $form data to the $rows
    // array, so that they end up as individual table cells when rendered
    // in the final table.  We run each element through the drupal_render()
    // function to generate the final html markup for that element.

    //drupal_set_message('Form: <pre>' . print_r($id, TRUE) . '</pre>');

    if (isset($form[$id]['name'])) {
      $rows[] = array(
        'data' => array(

          // Add our 'name' column.
          drupal_render($form[$id]['name']),

          // Add our 'description' column.
          drupal_render($form[$id]['type']),

          // Add our 'weight' column.
          drupal_render($form[$id]['weight']),

          drupal_render($form[$id]['operations']),
        ),

        // To support the tabledrag behaviour, we need to assign each row of the
        // table a class attribute of 'draggable'. This will add the 'draggable'
        // class to the <tr> element for that row when the final table is
        // rendered.
        'class' => array('draggable'),
      );
    }
  }

  // We now define the table header values.  Ensure that the 'header' count
  // matches the final column count for your table.
  $header = array(t('Name'), t('Type'), t('Weight'), t('Operations'));

  // We also need to pass the drupal_add_tabledrag() function an id which will
  // be used to identify the <table> element containing our tabledrag form.
  // Because an element's 'id' should be unique on a page, make sure the value
  // you select is NOT the same as the form ID used in your form declaration.
  $table_id = 'example-items-table';

  // We can render our tabledrag table for output.
  $output = theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array('id' => $table_id),
  ));

      // And then render any remaining form elements (such as our submit button).
      $output .= drupal_render_children($form);

      // We now call the drupal_add_tabledrag() function in order to add the
      // tabledrag.js goodness onto our page.
      //
      // For a basic sortable table, we need to pass it:
      // - the $table_id of our <table> element,
      // - the $action to be performed on our form items ('order'),
      // - a string describing where $action should be applied ('siblings'),
      // - and the class of the element containing our 'weight' element.
      drupal_add_tabledrag($table_id, 'order', 'sibling', 'example-item-weight');

      return $output;

}

/*function theme_edgemakers_stage_set_list_form($variables) {
  $form = $variables['form'];

  foreach (element_children($form['rows']) as $key) {
    $row = array();
    $row[] = array(
        'data' => drupal_render($form['rows'][$key]['title']),
    );
    $row[] = array(
        'data' => drupal_render($form['checkboxes'][$key]),
    );
    $rows[] = $row;
  }

  //$header = array('column_header_1', 'column_header_2');


  $header = array(
    'title' => array('data' => t('Set Title')),
    'type' => array('data' => t('Set Type')),
    'weight' => array('data' => t('Weight')),
    'operations' => array('data' => t('Delete')),
  );

  $output = theme('table', array(
    'header' => $header,
  ));

  $output .= drupal_render_children($form);
  return $output;
}*/

function edgemakers_set_index_delete_action($stage_id = '', $set_id) {

  $stage = node_load($stage_id);

  //drupal_set_message($stage_id . ' Stage index: <pre>' . print_r($set_id, TRUE) . '</pre>');

  if (isset($stage->box_index_data[LANGUAGE_NONE])) {
    $stage_index = unserialize($stage->box_index_data[LANGUAGE_NONE][0]['value']);

    //drupal_set_message('Stage index: <pre>' . print_r($stage_index, TRUE) . '</pre>');

    foreach ($stage_index AS $key=>$index) {
      if ($index['set_id'] == $set_id) {
        unset($stage_index[$key]);
      }
    }

    //unset($stage_index[$set_id]);

    //$stage['box_index_data'] = serialize($stage_index);
    // Update index data in stage.
    $stage->box_index_data[$stage->language][0]['value'] = serialize($stage_index);

    node_submit($stage);
    $save_status = node_save($stage);

    _edgemakers_stage_box_index_list_update($stage_id);

  }

}

//update setes list
function _edgemakers_stage_box_index_list_update($stage_id = '') {
  $output = _edgemakers_stage_mangebox_index_list_html($stage_id);
  $commands = array();
  $commands[] = ajax_command_replace('#stage_manage_box_index_list', '<div id="stage_manage_box_index_list">' . $output . '</div>');
  $page = array('#type' => 'ajax', '#commands' => $commands);
  ajax_deliver($page);
}

function _edgemakers_stage_mangebox_index_list_html($stage_id) {
  return drupal_render(drupal_get_form('edgemakers_stage_set_list_form', $stage_id));
}