<?php
/**
 * Implements hook_views_api().
 */
function edgemakers_topic_views_api() {
  return array(
    'api' => 3,
  );
}
/**
 * Implements hook_form_alter().
 *
}*/
function edgemakers_topic_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'taxonomy_form_term' && $form['vocabulary_machine_name']['#value'] == 'challenges_vocabulary') {
    unset($form['description']);
  }
}
/**
 * Implements hook_image_default_styles().
 */
function edgemakers_topic_image_default_styles() {
  $styles = array();

  $styles['edgemakers_topic_image'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array('width' => 200, 'height' => 150),
        'weight' => 0,
      ),
    )
  );

  return $styles;
}