<?php

/**
 * Implement hook_form_FORM_ID_alter().
 * FORM_ID == user_login
 */
function fteuser_form_user_login_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'fte_user_login_submit_handler';
}

function fte_user_login_submit_handler($form, &$form_state) {
  global $base_path;
  $form_state['redirect'] = 'home';
}

/**
 * Implement hook_form_FORM_ID_alter().
 * FORM_ID == user_register_form
 */
function fteuser_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  //dd($form['administer_users'],'qqq');
  if (isset($form['administer_users']) && isset($form['administer_users']['#value'])
          && $form['administer_users']['#value'] == TRUE) {
   // return;  // create user by backend 
  }

  // Ensure a valid submit array and validate array.
  $form['#submit'] = is_array($form['#submit']) ? $form['#submit'] : array();
  $form['#validate'] = is_array($form['#validate']) ? $form['#validate'] : array();
  // Replace core's registration function with FTEUSER registration function.
  // Put the FTEUSER submit handler first, so other submit handlers have a valid
  // user to work with upon registration.
  $key = array_search('user_register_submit', $form['#submit']);
  if ($key !== FALSE) {
    unset($form['#submit'][$key]);
  }
  //add role selector

  $langcode = isset($form['#language']) ? $form['#language'] : 'und';
  $r_list = user_roles(TRUE);
  $roles_array = array();
  $del_roles = array('authenticated user', 'site administrator', 'site admin', 'parent');
  $default_role = 0;
  foreach ($r_list as $k => $v) {
    if (!in_array($v, $del_roles)) {
      $roles_array[$k] = $v;
      if($v == 'student') $default_role = $k;
    }
  }
  unset($r_list);
  if (!empty($roles_array)) {
    $form['fte_assign_user_role'] = array(
      '#type' => 'radios',
      '#options' => $roles_array,
      '#title' => t('What is your role ?'),
      '#default_value' => $default_role,
      '#weight' => 15,
    );
  }
  //
  $form['#validate'][] = 'fteuser_user_register_validate';
  array_unshift($form['#submit'], 'fteuser_user_register_submit');
}
/**
 * custom validation function for the user registration form.
 */
function fteuser_user_register_validate($form, &$form_state) {
  $the_user_name = $form_state['values']['name'];
  $the_len = strlen($the_user_name); 
  if ($the_len < 4 || $the_len > 25 || preg_match("/[^A-Z|0-9|-]/i", $the_user_name) || preg_match("/^\d+$/", $the_user_name)) {
     form_set_error('name', '<br/><br/>User name should be at least 4 characters and 25 the most, cannot be fully numeric, and only allowed characters are Latin (A-Z) and Numbers (0-9), the - (hyphen) is also allowed.');
  }
}

function fteuser_user_register_submit($form, &$form_state) {

  $admin = $form_state['values']['administer_users'];
  $pass = $form_state['values']['pass'];  //password user input
  form_state_values_clean($form_state);
  $form_state['values']['pass'] = $pass;
  
  $form_state['values']['init'] = $form_state['values']['mail'];
  $account = $form['#user'];
  //$form_state['values']['pass']
  entity_form_submit_build_entity('user', $account, $form, $form_state);
  // Populate $edit with the properties of $account, which have been edited on
  // this form by taking over all values, which appear in the form values too.
  $edit = array_intersect_key((array) $account, $form_state['values']);


  if (!empty($form_state['values']['fte_assign_user_role'])) {
    $the_role_array[$form_state['values']['fte_assign_user_role']] = $form_state['values']['fte_assign_user_role'];
    foreach ($the_role_array as $k => $v) {
      if ($v != 0 && isset($edit['roles'][$k])) {
        $edit['roles'][$k] = 1;
      }
    }
  }
  
  $account = user_save($account, $edit);

  // Terminate if an error occurred during user_save().
  if (!$account) {
    drupal_set_message(t("Error saving user account."), 'error');
    $form_state['redirect'] = '';
    return;
  }
  $form_state['user'] = $account;
  $form_state['values']['uid'] = $account->uid;

  watchdog('user', 'New user: %name (%email).', array('%name' => $form_state['values']['name'], '%email' => $form_state['values']['mail']), WATCHDOG_NOTICE, l(t('edit'), 'user/' . $account->uid . '/edit'));

  // Add plain text password into user account to generate mail tokens.
  $account->password = $pass;
  $account->fteuserplainpass = $pass;
  $the_table = 'fteuserpass';
  $the_rec = new stdClass();
  $the_rec->uid = $account->uid;
  $the_rec->plainpass = $account->password;
 // drupal_write_record($the_table, $the_rec);
  db_merge($the_table)
      ->key(array('uid' => $the_rec->uid,))
      ->fields(array(
          'plainpass' => $the_rec->plainpass,
      ))
      ->execute();
  
  
  if (isset($form['administer_users']) && isset($form['administer_users']['#value'])
          && $form['administer_users']['#value'] == TRUE) {
    drupal_set_message('user created.');
  } 
  else {
    $message = t('A validation e-mail has been sent to your e-mail address. In order to gain full access to the site, you will need to follow the instructions in that message.');
    $mailkey = 'register_no_approval_required';
    _user_mail_notify($mailkey, $account);
    drupal_set_message($message);
    $form_state['redirect'] = 'home';
  }
  
 

  
  $mural_api = new Muralapi;
  
  fteuser_set_mural_user($mural_api, $account); //fte-501, create mural user at registeration
  
}

function fteuser_menu_alter(&$items) {
  $items['user/reset/%/%/%']['page callback'] = 'fteuser_userreset';

}

function fteuser_userreset($p, $uid, $timestamp, $hashed_pass) {

  watchdog('Invite Share', 'User reset in fteuser. and $p = ' . $p);

  global $user;
  global $base_url;

  if ($user->uid) {
    // The existing user is already logged in.
    if ($user->uid == $uid) {
      drupal_set_message(t('You are logged in as %user. <a href="!user_edit">Change your password.</a>', array('%user' => $user->name, '!user_edit' => url("user/$user->uid/edit"))));
    }
    // A different user is already logged in on the computer.
    else {
      $reset_link_account = user_load($uid);
      if (!empty($reset_link_account)) {
        drupal_set_message(t('Another user (%other_user) is already logged into the site on this computer, but you tried to use a one-time link for user %resetting_user. Please <a href="!logout">logout</a> and try using the link again.', array('%other_user' => $user->name, '%resetting_user' => $reset_link_account->name, '!logout' => url('user/logout'))));
      } else {
        // Invalid one-time link specifies an unknown user.
        drupal_set_message(t('The one-time login link you clicked is invalid.'));
      }
    }
    drupal_goto();
  } else {
    $current = REQUEST_TIME;
    $users = user_load_multiple(array($uid), array('status' => '0'));

    $account = reset($users);
    $account =  user_load($uid) ;

    if ($account) {
      $status = $account->status;
      if ($status == 1) {
        if ($account->uid && $timestamp >= $account->login && $timestamp <= $current && $hashed_pass == user_pass_rehash($account->pass, $timestamp, $account->login)) {
           $user = $account;
          user_login_finalize();
          $_SESSION['userchangepass'] = 1;
        }
      }
      else {
      if ($account->uid && $timestamp >= $account->login && $timestamp <= $current && $hashed_pass == user_pass_rehash($account->pass, $timestamp, $account->login)) {


        $account = user_save($account, array('status' => 1));
        if ($account) {
          $user = $account;
          user_login_finalize();
          $_SESSION['userreset'] = 1;
          drupal_set_message('<span class="firstlogin">'.t('You are now an EdgeMaker!').'</span>');
          if (empty($account->field_muralusername)) {
            // call the mural api : create user
            $mural_api = new Muralapi;
            fteuser_set_mural_user($mural_api, $account);
          }
        }
      }

    }

    }
  }

  // drupal_goto($base_url . "/welcome");
  drupal_goto($base_url . "/home");
}



function fte_user_logout($account) {
  global $base_url;
   $_SESSION['need_logout_muraleditor'] = 1;

}

/**
 * hook_user
 */
function fte_user_login(&$edit, $account) {
  $_SESSION['need_logout_muraleditor'] = 1;
  $edit['redirect'] = '';
}

function fteuser_set_mural_user($mural_api, $account) {
  $mural_user = array();
  $mural_user['username'] = $account->name;
  $mural_user['email'] = $account->mail;
  // $mural_user['email'] = "x16c3458@mail.com"; //test
  $the_org_str = variable_get('muralapi_org', 'edgemakers');
  $mural_user['source'] = $the_org_str;
  $mural_user['nameIdentifier'] = $account->uid;
  if (empty($account->fteuserplainpass)) {
     $account_uid = $account->uid;
            $account->fteuserplainpass = db_query("SELECT plainpass FROM {fteuserpass} WHERE uid = :uid", 
              array(':uid' => $account_uid))->fetchField();
      
  } 
  $mural_user['password'] = $account->fteuserplainpass;
  
  
  $mural_api_result = $mural_api->create_user($mural_user, '/api/organizations/' . $the_org_str . '/users', 'POST');
  //dd($mural_api_result);
  if (is_object($mural_api_result) && isset($mural_api_result->data)) {
    $muralapi_response_obj = drupal_json_decode($mural_api_result->data);

    if (isset($muralapi_response_obj['hasErrors'])) {
      if (!$muralapi_response_obj['hasErrors']) {
        // successful, then
        $edit = array();
        // the $muralapi_response_obj will contain the user attribute ($muralapi_response_obj->user)
        // but now ,it has no this attribute, so , just reguard the $account->name as the  mural username
        $the_mural_username = $account->name;
        if (isset($muralapi_response_obj['user'])) {
          if (isset($muralapi_response_obj['user']['username'])) {
            $the_mural_username = $muralapi_response_obj['user']['username'];

            $edit['field_muralusername'][LANGUAGE_NONE][0]['value'] = $the_mural_username;
          }
        }




        if (isset($muralapi_response_obj['room'])) {
          if (isset($muralapi_response_obj['room']['id'])) {
            $the_mural_roomid = $muralapi_response_obj['room']['id'];

            $edit['field_muralroomid'][LANGUAGE_NONE][0]['value'] = $the_mural_roomid;
          }
        }





        user_save($account, $edit);
        
        $profile_info = array();
        $avatarUris = explode('/', variable_get('user_picture_default', ''));
        $avatarUri = file_build_uri(array_pop($avatarUris));
        if(isset($account->field_profile_picture[LANGUAGE_NONE])) {
          $fid = $account->field_profile_picture[LANGUAGE_NONE][0]['fid'];
          if ($fid) {
            $profile_picture = file_load($fid);
            if (isset($profile_picture->uri)) {
              $avatarUri = $profile_picture->uri;
            }
          }
        }
        $profile_info['thumbUrl'] = rawurlencode(file_create_url($avatarUri));
        $profile_info['name'] = $account->field_firstname[LANGUAGE_NONE][0]['value'];
        $profile_info['surname'] = $account->field_lastname[LANGUAGE_NONE][0]['value'];
        //dd($profile_info);
        $mural_api->mural_profile_change($the_mural_username, $profile_info);

      }
    }
  }
}

/**
 * hook_field_attach_submit
 */
function fteuser_field_attach_submit($entity_type, $entity, $form, &$form_state) {
  if ($entity_type == 'user') {
   
    $the_uid = '';
    $the_plainpass = '';
    if (isset($entity->uid) && $entity->uid >= 1 ) {
     
      $the_uid = $entity->uid;
    }
    if (!empty($entity->pass)) {
      $the_plainpass = $entity->pass;
    }
    
    if ((int)$the_uid >= 1 && $the_plainpass != '') {
      $the_table = 'fteuserpass';
      
       db_merge($the_table)
      ->key(array('uid' => $the_uid,))
      ->fields(array(
          'plainpass' => $the_plainpass,
      ))
      ->execute();
    }
    
  }
}
