<?php
require_once 'edgemakers_set.pages.inc';
/**
 * Implements hook_menu().
 */
function edgemakers_set_menu() {
  $items['admin/edgemakers'] = array(
    'title' => 'Edgemakers',
    'page callback' => 'edgemakers_set_admin_page',
    'access arguments' => array('access content'),
  );
  $items['admin/edgemakers/set'] = array(
    'title' => 'Manage Set',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('edgemakers_set_admin_list_form'),
    'access arguments' => array('access content'),
  );
  $items['admin/edgemakers/set/list'] = array(
    'title' => 'Manage Set',
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/edgemakers/set/create'] = array(
    'title' => 'Create Set',
    'page callback' => 'edgemakers_set_admin_create_page', 
    'access arguments' => array('access content'),
    'file path' => drupal_get_path('module', 'node'),
    'file' => 'node.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/edgemakers/set/ajaxdelete/%'] = array(
    'title' => 'Delete Set',
    'page callback' => 'edgemakers_set_admin_delete_action',
    'page arguments' => array(4),
    'access arguments' => array('access content'),
    'file path' => drupal_get_path('module', 'node'),
    'file' => 'node.pages.inc',
  );
  return $items;
}
/**
 * Implements hook_form_alter().
 *
}*/
function edgemakers_set_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'edgemakers_set_node_form') {
    if(arg(0) == 'admin' && arg(1) == 'edgemakers' || arg(0) == 'modal') {
      $form['actions']['submit']['#submit'][] = 'edgemakers_set_node_submit_redirect_handler';
      $node = $form_state['node'];
      if (!isset($node->nid)) {
        //is node/add
        unset($form['actions']['preview']);
      } else {
        //is node/edit
        form_load_include($form_state, 'inc', 'node', 'node.pages');
        $form['field_set_type']['#disabled'] = TRUE;
        unset($form['actions']['preview'], $form['actions']['delete']);
      }
    }
    $langcode = isset($form['#language']) ? $form['#language'] : 'und';
    $form['field_set_type'][$langcode]['#after_build'] = array('_edgemakers_set_load_my_javascript');
    $form['actions']['#suffix'] = '<script>edgemakers_set_fields_update();</script>';
  }
}
/**
 * Implements hook_node_validate().
 *
 */
function edgemakers_set_node_validate($node, $form, &$form_state) {
  if($node->type == 'edgemakers_set') {
    $terms = _edgemakers_set_get_terms();
    $types = field_get_items('node', $node, 'field_set_type');
    $type = $types && count($types) > 0 ? $terms[$types[0]['tid']] : '';
    
    if($type != 'Project' && $type != 'Activity' && $type != 'Topic Page') {
      $urls = field_get_items('node', $node, 'field_set_url');
      $url = $urls && count($urls) > 0 ? $urls[0]['url'] : '';
      if($url == '') {
        form_set_error('field_set_url', t('Please fill in the URL'));
      }
    }
    if($type == 'Activity') {
      $bodys = field_get_items('node', $node, 'body');
      $body = $bodys && count($bodys) > 0 ? $bodys[0]['value'] : '';
      if($body == '') {
        form_set_error('body', t('Please fill in the Display text'));
      }
    } else if($type == 'Learn Module') {
      $images = field_get_items('node', $node, 'field_set_image');
      $image = $images && count($images) > 0 ? (isset($images[0]['width']) ? $images[0]['width'] : '') : '';
      if($image == '') {
        form_set_error('field_set_image', t('Please upload the Proxy Image'));
      }
    } else if($type == 'Topic Page') {
      $topics = field_get_items('node', $node, 'field_set_topic');
      $topic = $topics && count($topics) > 0 ? $topics[0]['target_id'] : '';
      if($topic == '') {
        form_set_error('field_set_topic', t('Please Select a Topic'));
      }
    }
  }
}