<?php
/**
 * Implements hook_menu().
 */
function fte_mapdemo_menu() {
  $items['Challenges'] = array(
    'page callback' => 'showchallengemap',
    'access callback'=> TRUE,
    'file' => 'fte_map.inc',      
  );
  
  return $items;
}
/**
 * Implements hook_theme().
 */
function fte_mapdemo_theme($existing, $type) {
  if ($type == 'module') {
    return array(
      'fte_challenge_map' => array(
        'variables' => array('data' => NULL),
        'template' => 'templates/challenge-map',
      ),
      'fte_marker_infowin' => array(
        'template' => 'templates/challenge-map-marker-infowin', 
        'variables' => array('data' => NULL), 
      ),  
    );
  }
  return array();
}
