<?php
/**
 * Implements hook_menu().
 */

function fte_menu() {
  $items['fteuserlogon'] = array(
    'page callback' => 'fteuserlogon',
    'access callback'=> TRUE,
    'type' => MENU_CALLBACK,  
  );
  $items['landingpage'] = array(
   
    'page callback' => 'show_landingpage',
    'access callback'=> TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['videodemo'] = array(
    'page callback' => 'show_videodemo',
    'access callback'=> TRUE,
    'type' => MENU_CALLBACK,  
  );
  
  return $items;
}
/**
 *page callback function. for langingpage link 
 */
function fteuserlogon() {
  global $user;
  $ret = '0';
  if ($user->uid > 0) {
    $ret = "1";
  } else {
    $ret = "0";
  }
  if (isset($_SESSION['userreset']) ) {
    //$ret = "2";
    unset($_SESSION['userreset']);
  }
  echo $ret;
  exit(0);
}
function show_landingpage() {
  global $user;
  if ($user->uid > 0) { //user logon
    //drupal_goto('node/1');
    
  }
  return theme('fte_landing_page');
}
function show_videodemo() {
  // mock data
  
  $current_yid = isset($_COOKIE['current_yid']) ? $_COOKIE['current_yid'] : '';
  $current_time = isset($_COOKIE['playtime']) ? $_COOKIE['playtime'] : 0;
  
  
  $youtube_video_data = array();
  $v1 = new stdClass();
  $v1->title = 'test1';
  $v1->yid = 'O5rTcz7EXEQ';
  $v1->play = 0;
  $v1->time = 0;
  $youtube_video_data[] = $v1;
  $v1 = new stdClass();
  $v1->title = 'test2';
  $v1->yid = 'wJ4iT0QQ1do';
  $v1->play = 0;
  $v1->time = 0;
  $youtube_video_data[] = $v1;
  $v1 = new stdClass();
  $v1->title = 'test3';
  $v1->yid = 'WTsfdROiotA';
  $v1->play = 0;
  $v1->time = 0;
  $youtube_video_data[] = $v1;
  
  if ($current_yid == '') {
    $youtube_video_data[0]->play = 1;
    
  } else { 
    $findflag = 0;
    foreach($youtube_video_data as $k=>$row) {
      if ($current_yid == $row->yid) {
        $youtube_video_data[$k]->play = 1;
        $youtube_video_data[$k]->time = $current_time;
        $findflag = 1;
        break;
      }
    
    }
    if ($findflag == 0) {
       $youtube_video_data[0]->play = 1;
    }
  }
  
  drupal_add_library('system', 'jquery.cookie');
  drupal_add_js(array('fte_video_demo' => $youtube_video_data), 'setting');
  $the_path = drupal_get_path('module', 'fte');
  drupal_add_js($the_path.'/js/fte_video_play.js');
  return theme('fte_video_demo',array('data'=>$youtube_video_data));

}
/**
 * Implements hook_theme().
 */
function fte_theme($exusting, $type) {
  if ($type == 'module') {
    return array(
      'fte_landing_page' => array(
      'variables' => array('data' => NULL),
      'template' => 'templates/landing-page',
      ),
      'fte_video_demo' => array(
      'variables' => array('data' => NULL),
      'template' => 'templates/fte-video-demo',
      ),
    );
  }
  return array();
}
