<?php
/**
 * Implements hook_menu().
 */

function fte_menu() {
  $items['fteuserlogon'] = array(
    'page callback' => 'fteuserlogon',
    'access callback'=> TRUE,
    'type' => MENU_CALLBACK,  
  );
  $items['home'] = array(
   
    'page callback' => 'show_landingpage',
    'access callback'=> TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['videodemo'] = array(
    'page callback' => 'show_videodemo',
    'access callback'=> TRUE,
    'type' => MENU_CALLBACK,  
  );
  
  
  
  
  return $items;
}

/**
 *page callback function. for langingpage link 
 */
function fteuserlogon() {
  global $user;
  $ret = '0';
  if ($user->uid > 0) {
    $ret = "1";
  } else {
    $ret = "0";
  }
  if (isset($_SESSION['userreset']) ) {
    //$ret = "2";
    unset($_SESSION['userreset']);
  }
  echo $ret;
  exit(0);
}
function fte_get_bg_image() {
  if(user_is_logged_in()) {
    global $user;
    $user = user_load($user->uid);    
    $images = field_get_items('user', $user, 'field_profile_background');
    $imageUri = $images && count($images) > 0 ? $images[0]['uri'] : '';
    if($imageUri) {
      return file_create_url($imageUri);
    }
  }
  return false;
}
function show_landingpage() {
  $image_path = fte_get_bg_image();
  if ($image_path !== false) {
    require_once drupal_get_path('module', 'bg_image').'/bg_image.module';
    bg_image_add_background_image($image_path);
  }
  $messages = drupal_get_messages();
  if(isset($messages['status'])) {
    $messages = $messages['status'];
    foreach($messages as $message) {
      if($message == t('A validation e-mail has been sent to your e-mail address. In order to gain full access to the site, you will need to follow the instructions in that message.') || $message == '<span class="firstlogin">'.t('You are now an EdgeMaker!').'</span>' || $message == t('Further instructions have been sent to your e-mail address.')) {
        drupal_set_message($message);
      }
    }
  }
  return theme('fte_landing_page');
}
function show_videodemo() {
  // mock data
  
  $current_yid = isset($_COOKIE['current_yid']) ? $_COOKIE['current_yid'] : '';
  $current_time = isset($_COOKIE['playtime']) ? $_COOKIE['playtime'] : 0;
  
  
  $youtube_video_data = array();
  $v1 = new stdClass();
  $v1->title = 'test1';
  $v1->yid = 'O5rTcz7EXEQ';
  $v1->play = 0;
  $v1->time = 0;
  $youtube_video_data[] = $v1;
  $v1 = new stdClass();
  $v1->title = 'test2';
  $v1->yid = 'wJ4iT0QQ1do';
  $v1->play = 0;
  $v1->time = 0;
  $youtube_video_data[] = $v1;
  $v1 = new stdClass();
  $v1->title = 'test3';
  $v1->yid = 'WTsfdROiotA';
  $v1->play = 0;
  $v1->time = 0;
  $youtube_video_data[] = $v1;
  
  if ($current_yid == '') {
    $youtube_video_data[0]->play = 1;
    
  } else { 
    $findflag = 0;
    foreach($youtube_video_data as $k=>$row) {
      if ($current_yid == $row->yid) {
        $youtube_video_data[$k]->play = 1;
        $youtube_video_data[$k]->time = $current_time;
        $findflag = 1;
        break;
      }
    
    }
    if ($findflag == 0) {
       $youtube_video_data[0]->play = 1;
    }
  }
  
  drupal_add_library('system', 'jquery.cookie');
  drupal_add_js(array('fte_video_demo' => $youtube_video_data), 'setting');
  $the_path = drupal_get_path('module', 'fte');
  drupal_add_js($the_path.'/js/fte_video_play.js');
  return theme('fte_video_demo',array('data'=>$youtube_video_data));

}
/**
 * Implements hook_theme().
 */
function fte_theme($exusting, $type) {
  if ($type == 'module') {
    return array(
      'fte_landing_page' => array(
      'variables' => array('data' => NULL),
      'template' => 'templates/landing-page',
      ),
      'fte_video_demo' => array(
      'variables' => array('data' => NULL),
      'template' => 'templates/fte-video-demo',
      ),
    );
  }
  return array();
}



/**
 * Implement hook_form_FORM_ID_alter().
 * FORM_ID == mass_contact_mail_page
 */
function fte_form_mass_contact_mail_page_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'fte_mass_contact_mail_page_submit_handler';
}

function fte_mass_contact_mail_page_submit_handler($form, &$form_state) {
  global $base_path;
 
  $form_state['redirect'] = 'home';
}
function fte_menu_alter(&$items) {
  $items['node/add/webform']['description'] = '';
  $items['mass_contact']['description'] = '';
  $items['admin/people']['description'] = '';
  
}